[package]
name = "ngram-demo"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
sucds = "0.8.1"
yada = "0.5.0"
